### ISSUE TITLE
The template doesn't disappear when the navigate component

### ISSUE THREAD

**Issue by daitd58** [surveyjs/surveyjs_angular_cli#1]
Hi @tsv2013, I have an issue with the survey block. I see the survey library generate html dom out of current component so when the component is navigated the survey block doesn't disappear. Any advice? Thanks.

**Comment by tsv2013** [comment]
@daitd58 Could you specify what do you mean? Can you give me your survey json or exact steps to reproduce wrong behaviour in this project?

**Comment by daitd58** [comment]
@tsv2013 I view the survey template using the editor text. I have component ViewSurvey when I navigate to it which display the survey template but when I navigate to others component the survey template still display. And I see the survey html dom is out of ViewSurvey tag so when the ViewSurvey tag disappear but the survey template doesn't..

**Comment by tsv2013** [comment]
@daitd58 Can you give me an example to reproduce the issue? Or link to your repo? I would like to see your page layout (markup).
You can just place Survey tag to any other place of your markup which will be hidden in case of navigation to other view.

**Comment by daitd58** [comment]
@tsv2013 you can view it on this repo: https://github.com/daitd58/surveyApp. I have component ViewTemplatePage. Thanks.

**Comment by tsv2013** [comment]
@daitd58 ok, i'll check it.

**Comment by daitd58** [comment]
Thanks.

**Comment by daitd58** [comment]
@tsv2013 Did you check it?

**Comment by tsv2013** [comment]
@daitd58 Not yet. Cloning your repo right now.

**Comment by daitd58** [comment]
@tsv2013 thanks. Hope you can give me some advice.

**Comment by tsv2013** [comment]
@daitd58 Ran your project. Did the following steps:
1. Clicked on "Surveys" -> empty surveys list is shown
2. Clicked on "Create New" -> choose "From Blank Survey" -> SurveyJS editor is shown
3. Filled "Title" field, droped checkbox, clicked "Save Survey" -> hothing happened
4. Clicked on "Surveys" -> empty surveys list is shown

Could you tell me what steps should I perform to reproduce the issue?

**Comment by daitd58** [comment]
Hi, you can make an example survey on any component. And It still display on other component. Such as: make example survey on ViewSurveyPage and that survey still display on other component like ListSurveyPage....

**Comment by tsv2013** [comment]
@daitd58  How can I navigate to the ViewSurveyPage? What url should I type?

**Comment by daitd58** [comment]
@tsv2013 You can click on icon eye in the list survey

**Comment by tsv2013** [comment]
@daitd58  If I navigate to "/survey/view", I get the error:

> Unhandled Promise rejection: Cannot match any routes. URL Segment: 'survey/view' ; Zone: angular ; Task: Promise.then ; Value: ZoneAwareError {__zone_symbol__error: Error: Cannot match any routes. URL Segment: 'survey/view'
>     at ApplyRedirects.noMatchError (http:……} Error: Cannot match any routes. URL Segment: 'survey/view'

**Comment by tsv2013** [comment]
@daitd58  Where can I find the eye icon? Surveys list is always empty. Even after I click "Save Survey" in the editor:
![image](https://cloud.githubusercontent.com/assets/3013415/24693990/d2ae8374-19e8-11e7-8464-bc2cfbecb79e.png)

**Comment by daitd58** [comment]
For simple. You can make an example survey on TemplateComponent and navigate to SurveyComponent and see what happen. I mean the survey still display when you navigate to other component.

**Comment by daitd58** [comment]
@tsv2013 Any news? Thanks.

**Comment by tsv2013** [comment]
@daitd58 Triyng to follow your instructions :)

**Comment by daitd58** [comment]
@tsv2013 I see the survey lib generate HTML DOM out of current component tag so when the component disappear but the survey HTML doesn't. :)

**Comment by tsv2013** [comment]
@daitd58  I've added sample survey to the Surveys list page and then navigate to another page, survey markup goes away. I can fork your repo and create a pull request. Or you can inspect my fork. What will be more convinient for you?

**Comment by tsv2013** [comment]
@daitd58 You can check the https://github.com/tsv2013/surveyApp/commit/25a6f3548d5ccc97fa4e8a14126e981d92da7ca3 commit. Survey is visible on "surveys list" page, but invisible on other pages.

**Comment by daitd58** [comment]
@tsv2013 I will check it.

**Comment by ReneI** [comment]
> @tsv2013 I will check it.

your application already works? i can see your code?

**Comment by dmitry-kurmanov** [comment]
@ReneI  Hello! @daitd58 's repo is open source for the moment so you can check it https://github.com/daitd58/surveyApp
