### ISSUE TITLE
[complete] button event

### ISSUE THREAD

**Issue by mkgn** [surveyjs/surveyjs_angular_cli#10]
Hi,

In the sample; this.editor.saveSurveyFunc gets call whenever the form design changes. 
When i test the form at the end of it [complete] button should raise an event as well.

I tried attaching an event to this.editor.saveButtonClick but doesn't work. In the documentation it shows that there is a onComplete method. I couldn't find it in editor instance. Which event should I implement to for the [complete] button at the end of the survey? That is where I am planning to send my data to server.

**Comment by tsv2013** [comment]
The [onComplete](https://surveyjs.io/Documentation/Library/?id=surveymodel#onComplete) event belongs to a survey object, not a survey editor.

You can find this event almost in any example on our site:
```JS
survey
    .onComplete
    .add(function (result) {
        document
            .querySelector('#surveyResult')
            .innerHTML = "result: " + JSON.stringify(result.data);
    });
```

This code is taken from this example - https://surveyjs.io/Examples/Library/?id=questiontype-text&platform=Angular2

**Comment by mkgn** [comment]
Thanks! got it sorted
