### ISSUE TITLE
Uncaught TypeError: Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by AquilaH** [surveyjs/surveyjs_angular_cli#11]
Good Day, 

I get an error when I try to run the application and I'm getting difficulty finding a solution to it. 

Please image below.

![uncaught typeerror](https://user-images.githubusercontent.com/32176411/41552656-acecf4ee-732f-11e8-8095-6258d604fe08.JPG)

**Comment by tsv2013** [comment]
I've checked this repo (clone it, run "npm i", run "ng serve") - it works ok for me.
It looks like in your application jquery is not loaded on your page.

This is described in the readme file:

> 7. Add "jQuery polyfill" for bootstrap in the polyfills.ts file (https://github.com/angular/angular-cli/issues/2129).
> ```JS
> import * as jQuery from 'jquery';
> window['jQuery'] = jQuery;
> ```

**Comment by AquilaH** [comment]
Good Day,

Thank you for this... I followed the solution provided on the link you referenced and was able to get my application to work!!! :)


https://github.com/angular/angular-cli/issues/2129#issuecomment-334701987

**Comment by mrjamiebowman** [comment]
Adding it as a polyfill worked for me! Great stuff! Thanks

**Comment by GerkinDev** [comment]
To provide *jQuery* in *karma*+*jasmine* tests, add it to the `files` array of your *karma* config (in `karma.conf.js`):

```js
module.exports = config => {
	config.set({
		// ...
		files: [
			"node_modules/jquery/dist/jquery.js",
			// ... Other script files of surveyjs that causes you errors
		],
		// ...
	});
};
```

> Note: more generaly, you may want to do this for all `scripts` dependencies. I don't know if it's really a good option but I'm a bored man who would disgust to add files manually. So I did that:
>
> ```js
> module.exports = config => {
> 	config.set({
> 		// ...
> 		files: require('./angular.json').projects['TODO-my-project-name'].architect.build.options.scripts,
> 		// ...
> 	});
> };
> ```
