### ISSUE TITLE
ERROR TypeError: Unable to process binding "template: function (){return { name:'objecteditorproperty',afterRender:$parent.koAfterRender} }"

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [surveyjs/surveyjs_angular_cli#12]
while integrating in angular 5 application i'm getting below error , Please help me out to fix this error

**ERROR TypeError:** Unable to process binding "template: function (){return { name:'objecteditorproperty',afterRender:$parent.koAfterRender} }"
Message: Unable to process binding "template: function (){return { name:'propertyeditor-'+ editorTypeTemplate,data:$data.editor} }"
Message: Unable to process binding "template: function (){return { name:'propertyeditor-modal',data:$data} }"
Message: Unable to process binding "template: function (){return { name:'propertyeditor-modalcontent',data:$data} }"
Message: Unable to process binding "template: function (){return { name:'propertyeditorcontent-'+ editorTypeTemplate,data:$data,afterRender:$data.koAfterRender} }"
Message: Cannot read property 'replace' of undefined
    at Object.afterRender (survey-editor-component.ts:24)
    at SurveyPropertyModalEditorCustomWidget.afterRender (surveyeditor.js:640)
    at SurveyPropertyHtmlEditor.SurveyPropertyModalEditor.afterRender (surveyeditor.js:785)
    at SurveyPropertyModalEditor.self.koAfterRender (surveyeditor.js:712)
    at Object.ignore (knockout-latest.debug.js:1480)
    at executeTemplate (knockout-latest.debug.js:5351)
    at ko.dependentObservable.disposeWhen (knockout-latest.debug.js:5391)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout-latest.debug.js:2183)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout-latest.debug.js:2150)

**Comment by dmitry-kurmanov** [comment]
@BhuvaneshwaranR hello! Sorry for the late response. Do you have the error with this repo(https://github.com/surveyjs/surveyjs_angular_cli) ?

**Comment by BhuvaneshwaranR** [comment]
@dmitrykurmanov Yes. Can you please check the mentioned error above?

**Comment by dmitry-kurmanov** [comment]
@BhuvaneshwaranR ok I will clone our repo and will run it from the scratch.

**Comment by BhuvaneshwaranR** [comment]
@dmitrykurmanov  Thank you.

**Comment by dmitry-kurmanov** [comment]
@BhuvaneshwaranR I've cloned the repo and ran it. I don't see any errors. May be the problem in your specific code? Could you please share a small example to reproduce the problem?

**Comment by BhuvaneshwaranR** [comment]
@dmitrykurmanov.I will check and share the code if i get any issue.  One of our client want to integrate surveyJS in their application. We would like to know  features of surveyJS. Is there is any quick support available ?

**Comment by dmitry-kurmanov** [comment]
@BhuvaneshwaranR you can find all features description on our site:

**builder** overview: https://surveyjs.io/Documentation/Builder/
**library** overview: https://surveyjs.io/Documentation/Library/
also you can find docs and examples there.

As for support SurveyJS project, it supported by full-timed professtional team. Also you can ask your questions in our support center: https://surveyjs.answerdesk.io/

**Comment by BhuvaneshwaranR** [comment]
@dmitrykurmanov  Thanks for your quick reply. :+1:
