### ISSUE TITLE
Integration issue on existing angular 5 application - breaks UI

### ISSUE THREAD

**Issue by BhuvaneshwaranR** [surveyjs/surveyjs_angular_cli#13]
While integrating surveyJS in existing angular application, it breaks the UI of surveyJS builder and SurveyJS form. I have removed the existing custom style file and recompiled it but nothing works. Please help me out to integrate surveyJS in existing angular 5 application.
![ui breaks](https://user-images.githubusercontent.com/10132578/42202965-f38d5f38-7eba-11e8-8812-cb6f0c9de3a2.png)

**Comment by tsv2013** [comment]
It looks like `surveyeditor.css` and `survey.css` styles from the packages haven't been loaded.
You can check the https://github.com/surveyjs/surveyjs_angular_cli/blob/master/.angular-cli.json file:
```JSON
      "styles": [
        "styles.css",
        "../node_modules/bootstrap/dist/css/bootstrap.min.css",
        "../node_modules/survey-angular/survey.css",
        "../node_modules/surveyjs-editor/surveyeditor.css",
```

**Comment by BhuvaneshwaranR** [comment]
@tsv2013  It's working now. Thank you :+1:
