### ISSUE TITLE
input masking not showing on text input

### ISSUE THREAD

**Issue by Satya-Yelamanchili** [surveyjs/surveyjs_angular_cli#18]
Added the phone input masking to the text but the input doesn't show the masking on when try to enter the phone  number. It is happening with all the masking inputs.
![image](https://user-images.githubusercontent.com/29648751/55098301-88f5d800-508b-11e9-9708-55c8e26f74f2.png)

![image](https://user-images.githubusercontent.com/29648751/55098188-564bdf80-508b-11e9-8a77-6bbed3ed74ad.png)

![image](https://user-images.githubusercontent.com/29648751/55098239-6c59a000-508b-11e9-86da-61900ae749a5.png)

**Comment by tsv2013** [comment]
Have you set up your survey JSON properly? Please check this sample - https://surveyjs.io/Examples/Library/?id=custom-widget-inputmask&platform=Angular2&theme=default
