### ISSUE TITLE
Question, can use survey-knockout, survey-angular and surveyjs-widgets for free?

### ISSUE THREAD

**Issue by iamfariba** [surveyjs/surveyjs_angular_cli#22]
Hi,

I would like to ask you  "survey-knockout": "^1.0.20", "survey-angular": "^1.0.20" and "surveyjs-widgets": "^1.0.20" can be used for free?

Thank you

**Comment by tsv2013** [comment]
Yes, you can use survey-knockout, survey-angular and surveyjs-widgets packages for free. But surveyjs-widgets depends on 3rd party libraries. Please ensure your usage doesn't violate corresponding 3rd party libraries licenses.
