### ISSUE TITLE
Can't build with ng build --prod --build-optimizer=true

### ISSUE THREAD

**Issue by thaotx** [surveyjs/surveyjs_angular_cli#27]
I'm follow README.md to create a simple survey with angular. 
But I can't build with ng build --prod --build-optimizer=true.
When I remove  --build-optimizer=true, it runs normally. 
Please help to check it.

**Comment by tsv2013** [comment]
I've checked it on my machine, and this command stucks at 30% with no error messages or other useful info. I've googled a bit and found a lot of issues in the angular-cli repo: https://github.com/angular/angular-cli/issues/12989, https://github.com/angular/angular-cli/issues/9779, https://joeonsoftware.com/2018/10/04/stuck-on-92-chunk-optimization-on-angular-production-builds/
It looks like the issue is more related to angular-cli then to SurveyJS. I've tried to use advices from this threads, but no luck. Now I leave this issue opened until we'll get any addiiotnal info.

**Comment by carstenbaumhoegger** [comment]
I'm also experiencing this issue.
I've used `v1.0.81` before and updated to `v1.0.89`. Building the application is impossible then.
I also looked at the links provided by @tsv2013 but nothing helped.
Reverting to `v1.0.81` resolved this issue for now. I haven't changed Angular CLI etc. so it seems that this is related to `SurveyJS`

**Comment by krasende** [comment]
I'm also experiencing this issue...

Just for the record, `node --max_old_space_size=8192 $(which ng) b --buildOptimizer=true --aot` doesn't help.

**Comment by carlosgoce** [comment]
I migrated from Angular5 to Angular7 and when I tried to build for production it happened to me also.
The build process is stuck on surveyjs. I am on version ~1.0.54 but It's happening on version v1.0.81 too.

```
 69% building 1238/1240 modules 2 active ...odules/survey-angular/survey.angular.js
```

It's there forever. 
On Angular5 builds just fine with or without built-optimizer.

**Comment by rkdhanyakula** [comment]
I am facing the same issue when using Angular 7, Any solutions? 
![image](https://user-images.githubusercontent.com/8548516/59990455-d2979400-9675-11e9-9710-2ac244427c67.png)

**Comment by rkdhanyakula** [comment]
> I am facing the same issue when using Angular 7, Any solutions?
> ![image](https://user-images.githubusercontent.com/8548516/59990455-d2979400-9675-11e9-9710-2ac244427c67.png)

Reverting to v1.0.81 resolved this issue for now.

**Comment by tsv2013** [comment]
Also discussed  in this thread - https://surveyjs.answerdesk.io/internal/ticket/details/T2222
Builds with 1.0.85
Not builds since 1.0.87
peg.js generated code has been added in 1.0.87

**Comment by tsv2013** [comment]
The issue was caused by too much nested `if() {}` conditions in the `peg$parseComparableOperators` autogenerated function. I think ng builder/optimizer need some improvements indeed.
The fix will be available in the nearest update.
