### ISSUE TITLE
keep recompiling 

### ISSUE THREAD

**Issue by kutaibah** [surveyjs/surveyjs_angular_cli#3]
after install it keeps recompiling ?

**Comment by tsv2013** [comment]
Unfortunately, no. I'll take a look.

**Comment by tsv2013** [comment]
I've added some dependencies in the 31a4518b84358cf07bf1a010ebf6b203e95d70b4 commit. After reinstalling node modeules it works ok for me. @kutaibah  Can you check it?

**Comment by kutaibah** [comment]
sorry but it still with the same issue 

the steps:
1- git clone https://github.com/surveyjs/surveyjs_angular_cli my_project
2- cd my_project && npm install
3- npm start or ng serve

it keeps recompiling around 10 times

**Comment by kutaibah** [comment]
Solved!
the problem was old node version 

thanks for support @tsv2013

**Comment by tsv2013** [comment]
Excellent!

**Comment by tsv2013** [comment]
@kutaibah Please feel free to contact us!
