### ISSUE TITLE
Angular package (survey-angular) has dependency on knockout? ko not defined

### ISSUE THREAD

**Issue by rishikeshjadhav** [surveyjs/surveyjs_angular_cli#33]
Getting issue with ko not defined

1. Created empty angular application using Angular CLI
2. Followed steps in README
3. On ng serve getting error with knockout objects "ko undefined"

**Comment by rishikeshjadhav** [comment]
Once i add the survey-knockout package this error in no more occuring.

Is there a dependency of knockout with survey-angular package?

**Comment by tsv2013** [comment]
SurveyJS Creator uses KnockoutJS library

**Comment by rishikeshjadhav** [comment]
Hi @tsv2013 , Thanks for your quick response.

But i am not using "survey-creator" package, i am using "survey-angular" and "surveyjs-widgets" packages in an angular application.

If i install only "survey-angular" and "surveyjs-widgets" packages i get the error with ko objects, but if i install "survey-knockout" package which internally installs knockout packages this error is not observed.

So i would like to know if it is possible to only use "survey-angular" and "surveyjs-widgets" packages and get surveys running?

**Comment by tsv2013** [comment]
Yes, survey-angular and survey-widgets don't require KnockoutJS

To be more precise, the survey-angular package based upon the survey-knockout and contains survey-knockout and KnockoutJS library bundled inside. That's why it shouldn't require KnockoutJS.
If it isn't so, most likely we need to fix it.

**Comment by rishikeshjadhav** [comment]
Yes that is not happening currently. 

The knockout dependencies are not getting installed when i install survey-angular package.

I have explicitly added the survey-knockout package and moved ahead.

It will be good to get this fixed. 

Thanks for the quick response again.

**Comment by tsv2013** [comment]
Note, that is you exactly followed the steps from the readme file of this repo, you added the survey-creator package, that depends on survey-knockout.

**Comment by rishikeshjadhav** [comment]
> Hi @tsv2013 , Thanks for your quick response.
> 
> But i am not using "survey-creator" package, i am using "survey-angular" and "surveyjs-widgets" packages in an angular application.
> 
> If i install only "survey-angular" and "surveyjs-widgets" packages i get the error with ko objects, but if i install "survey-knockout" package which internally installs knockout packages this error is not observed.
> 
> So i would like to know if it is possible to only use "survey-angular" and "surveyjs-widgets" packages and get surveys running?

No, i am not using creator package as i don't need it.

**Comment by mezzo1981** [comment]
Hi, 
@tsv2013 we have now the same problem with "survey-angular": "^1.7.18",

`ERROR in node_modules/survey-angular/survey.angular.d.ts:8:21 - error TS2307: Cannot find module 'knockout' or its corresponding type declarations.`

**Comment by tsv2013** [comment]
@mezzo1981 I've fixed it via referenced commit. Fix will be available in 1.7.19

**Comment by mezzo1981** [comment]
@tsv2013 wow that was quick

**Comment by carolcarpenter** [comment]
Survey JavaScript library v1.8.26 is requiring knockout. Is there a fix for this?

**Comment by ghost** [comment]
It looks like this issue is occurring again in the latest release... Survey JavaScript library v1.8.26. It is requiring knockout. Is there a fix for this on the way? Thanks!
@tsv2013
