### ISSUE TITLE
UI gets distorted upgrading survey-angular from 1.0.7 to 1.5.19

### ISSUE THREAD

**Issue by omkark** [surveyjs/surveyjs_angular_cli#38]
I have upgraded survey-angular and its dependencies survey-knockout and survey-widgets from version 1.0.7 to 1.5.19

While building I was getting knockout issues while compiling. It got fixed by removing types/knockout and installing knockout@3.4.2

On rendering survey, ui is getting disrotted.

eg: jquery datepicker icon placement is distorted. Also could not see background for error messages. Also fonts style got changes.

![image](https://user-images.githubusercontent.com/6219821/80335609-67f54d00-8872-11ea-8fae-f2a058d398b8.png)

**Comment by tsv2013** [comment]
I've just checked this repo:
```
git clone https://github.com/surveyjs/surveyjs_angular_cli.git surveyjs-angular-cli
cd surveyjs-angular-cli
npm i
npm start
```

It loads survey libraries with v1.7.3, build and works ok for me

Can ou provide the exact steps to reproduce the issue?

**Comment by omkark** [comment]
We are using Angular 4. 
Previously we were using:
        "survey-angular": "^1.0.7",
        "survey-knockout": "^1.0.7",
        "surveyjs-widgets": "^1.0.7"
All our surveys working as expected. Then we upgraded above libraries to v1.5.19 and getting above issue.

In code, previously bootstrap was injected using cssType. With new library we have to do it using:
      Survey
      .StylesManager
      .applyTheme("bootstrap"); 

Thats the only change we did. Please suggest if there are any pointers

**Comment by tsv2013** [comment]
This demo repo works ok. It's hard to say what's wrong with your code. You can compare your code with code from this repo to find what works wrong.
