### ISSUE TITLE
Unable to Run Project

### ISSUE THREAD

**Issue by alkrobinson** [surveyjs/surveyjs_angular_cli#46]
I have tried to download and install and then serve the project as is and it runs into the Schema validation error shown below 

![image](https://user-images.githubusercontent.com/26122765/90794912-05b5d180-e2d3-11ea-8c39-beffb23e023c.png)

Then i try to upgrade everything and then run it  and i get a memory error as shown below 

![image](https://user-images.githubusercontent.com/26122765/90795051-3564d980-e2d3-11ea-87a9-102812461dfa.png)

I have tried to run this project on Linux and Windows operating systems with these failures. Any suggestions on how to get it up and running?

**Comment by dmitry-kurmanov** [comment]
I've tried to clone and run the project and it works ok for me. Here the commands I used:

```
git clone https://github.com/surveyjs/surveyjs_angular_cli.git
cd surveyjs_angular_cli
npm i
npm start
```

Also could you please specify what version of nodejs do you currently use? (mine is 10.17.0)

_By the way we should update the [Readme](https://github.com/surveyjs/surveyjs_angular_cli/blob/master/README.md) ._

**Comment by alkrobinson** [comment]
ok there is a difference between ng serve and npm start.

**Comment by dmitry-kurmanov** [comment]
in fact there is no difference because `npm start` calls `ng serve`. Please check the package.json scripts section:

```js
 "scripts": {
     ...
    "start": "ng serve",
    ...
```
