### ISSUE TITLE
Boilerplate makes constant calls to `http://localhost:4200/undefined`

### ISSUE THREAD

**Issue by wollerman** [surveyjs/surveyjs_angular_cli#5]
I cloned this repo and ran it locally on port 4200 by doing the following:
```
git clone
cd surveyjs_angular_cli
npm install
ng serve
```
Checking the dev console I see constant calls to `http://localhost:4200/undefined`

**Comment by tsv2013** [comment]
@wollerman I can't reproduce it. All works like a charm. What's your Angular CLI version?

**Comment by wollerman** [comment]
Here's the full output of `ng --version`:
```
 ~/sandbox/surveyjs_angular_cli$ ng --version
Your global Angular CLI version (1.6.4) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 9.4.0
os: darwin x64
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.0.0
@angular/compiler-cli: 4.4.6
```

Looking at the `package.json` it specifies `1.0.0` which is why I get that warning about global vs local.

**Comment by wollerman** [comment]
I started up the project with `ng serve` and then opened chrome devtools and see: 
![image](https://user-images.githubusercontent.com/1610241/35232694-026ecee0-ff51-11e7-8cb4-377c84c81eab.png)

It seems to think it's an image of some kind?

**Comment by ShadowFoOrm** [comment]
I m having the same problem `http://localhost:4200/undefined` but I get an extra error in Console.
![image](https://user-images.githubusercontent.com/13979327/35234498-3f2e795a-ff99-11e7-88e4-d4e2fef0b17c.png)

**Comment by tsv2013** [comment]
I've fixed "undefined" request from signature pad custom widget and updated package versions.

**Comment by wollerman** [comment]
Thanks for all the quick fixes!
