### ISSUE TITLE
Angular package (survey-angular) should not have a dependency on knockout

### ISSUE THREAD

**Issue by ghost** [surveyjs/surveyjs_angular_cli#52]
Regarding Issue: Angular package (survey-angular) has dependency on knockout? ko not defined **#33**

It looks like this issue is occurring again in the latest release... Survey JavaScript library v1.8.26. It is requiring knockout. Is there a fix for this on the way?

**Comment by tsv2013** [comment]
Thank you for the report. We're working on the fix and update this thread as soon as we'll have any results.

**Comment by tsv2013** [comment]
I've added check in our build pipeline.
+ Temporary fixed typings

Good fix will be after ActionBar/Popup/List models will be implemented in platform-independent way
