### ISSUE TITLE
Please Elaborate the steps 4 in WIKI

### ISSUE THREAD

**Issue by riginoommen** [surveyjs/surveyjs_angular_cli#6]
* Add SurveyJS and Editor components files.
 where we should add the files

**Comment by tsv2013** [comment]
If you creating your own application, this is up to you - you can put prepared components in the appropriate folder of your project.

If you want to start this demo application, you should:
 - clone this repo
 - make the repo folder your current folder
 - run `npm i`
 - run `ng serve`
