### ISSUE TITLE
Is survey-angular-ui stable?

### ISSUE THREAD

**Issue by otebos** [surveyjs/surveyjs_angular_cli#66]
Hi,
I've been using survey-angular in my project for few months and just found out survey-angular-ui.
It's great you are making this angular-based version!

Question: is it fully functional and stable like survey-angular and I can think of migration?
Or should wait few months?

Regards,
o.

**Comment by JaneSjs** [comment]
Hello,
Yes, we released an early version of Survey Creator V2 for Angular. We are continue making some slight final API changes.
For now, you can built a demo app using the [survey-creator-angular](https://www.npmjs.com/package/survey-creator-angular) package and try our Survey Creator for Angular.

Should you encounter any issues, please feel free to contact us.

**Comment by otebos** [comment]
Hi,
I switched today and everything seems to work so thank you and great job 👍

**Comment by dk981234** [comment]
Hello,

We have changed some APIs according to this issue: https://github.com/surveyjs/survey-creator/issues/3623 from version 1.9.56. We have updated the example.

Thanks,
Dmitry
SurveyJS Team
