### ISSUE TITLE
Save the results of a survey

### ISSUE THREAD

**Issue by vitortk8** [surveyjs/surveyjs_angular_cli#8]
Hello, 

I am new to the surveyjs

Can you help me on how to save the results of a survey in a JSON file for example

Thanks in Advance

Vítor Costa

**Comment by bramson** [comment]
I also have this question.  In your examples you show how to print the resulting JSON to the screen, but I don't know how to simply save them to a file (e.g. in the directory where the webpage with the survey is located).

**Comment by tsv2013** [comment]
@vitortk8 Sorry, I lost this question.
SurveyJS library works in a browser.
The question is out of SurveyJS library scope.
I've googled the "javascript save file from a browser"
And the first link looks good for me - https://stackoverflow.com/questions/13405129/javascript-create-and-save-file
Hope, this helps
